var GAME_LEVELS = [
  ["                                                                                  ",
   "  x                                                                               ",
   "  x    x         x                                                              ",
   "  x    x  x x    x                                                                 ",
   "  x    x  x x    x                                                                  ",
   "  x    x   x  x  x                                                                ",
   "  x                                     y                                         ",
   "  x                                        o                                      ",
   "  x                            y          xxx                                     ",
   "  x                                o     xxxxx                                    ",
   "  x                           o   xxx   xxxxxxx                y     y            ",
   "  x                     o    xxx                  |               |      |     o   ",
   "  x                    xxxx               y y                                  o   ",
   "  x   @     o        xxx!!x                       !  xxxxxx       !      !     o   ",
   "  xxxxxxxxxxxxxx!!!xxxxx!!xxxxxxxxxxxxxxxxxxxxxxx!!!xx    xxxxxxx!!!xxxx!!!xxxxxxx ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   "                                                                                   ",
   "                                                                                  ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   "],
  ["                                                                                                                      ",
  "                                                                                                                     o ",
  "                                                                                                                     o ",
  "                                                                                                                 oxxxx ",
  "                                                                                                                oxxxxx ",
  "                                                                                                                xxxxxx ",
   "   x                                                                                   o             =        xxxxxxx ",
   "   x  x x    x x                                  o                                 xx o xx                  xxxxxxxx ",
   "   x  x x    x x                                                         o          x  o  x                 xxxxxxxxx ",
   "   x   x  x  x x                                 xxxx        o                      x     x              xxxxxxxxxxxx               ",
   "                                                            xxx                    x       x             x=  =                ",
   "                                 o         o                                       x       x           o x                   ",
   "                     xxxxxx              xxxxx                      xxxx     xxxxxx        xxxxxxx  o  xxx                   ",
   "                     x!!!!x                        |                                                                          ",
   " =     =    @                  xxxxx                                                                                          ",
   "         xxxxxxxx     ooo                                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             ",
   "xxxxxxxxxx!!!!!!xxxxxxxxxxxxx!!!!!                 |                                                                                ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                             ",
   "                                                                                                              ",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             ",
"     x                                                                                                          ",
"     x  x x    x x x                                                                                            ",
"     x  x x    x x x                                                                                            ",
"     x   x  x  x x x                                                                                            ",
  "                                                                                                              ",
  "                                                                                                      x  ",
  "                                                                                                      x  ",
  "                                                                                                      x  ",
  "                                o  o                                                                  x  ",
  "                              o xxxxxx                                                       o        x         ",
  "                 o          o xxx    xxx                                                  xxxxxxx     x              ",
  "                           xxx         xxx                                                            x     ",
  "                      o                        xxxxx=                  x          x                   x        ",
  "                 |   xxx                                xxx                      xxx                  x          ",
  "    @       xxx                                               xx               xxxxxxx                x             ",
  " | xxxx  |       |                                                                                    x       ",
  " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
  " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
